### ISSUE TITLE
请教下大佬

### ISSUE THREAD

**Issue by linjialiang** [AlloyTeam/eslint-config-alloy#207]
用你这个，vue3+ts的验证该怎么配置吗？
文档里没有对vue3+ts的配置进行说明

比如我在vite脚手架里如何配置？

- .eslintrc.yaml

  ```yaml
  env:
    vue/setup-compiler-macros: true
  extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:vue/vue3-recommended'
    - 'plugin:prettier/recommended'
  parser: 'vue-eslint-parser'
  parserOptions:
    parser: '@typescript-eslint/parser'
    ecmaFeatures:
      jsx: true
    ecmaVersion: latest
  ```

- package.json

  ```json
  ...
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.3.1",
    "@typescript-eslint/parser": "^5.3.1",
    "@vitejs/plugin-vue": "^1.9.3",
    "eslint": "^8.2.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-vue": "^8.0.3",
    "typescript": "^4.4.4",
    "vite": "^2.6.4",
    "vue-tsc": "^0.3.0"
  }
  ...
  ```
